# Generated by Django 4.2.5 on 2023-12-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.TextField(default='Admin not provide any discription'),
            preserve_default=False,
        ),
    ]
